<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="8.0.11" />

  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Platform.Domain\Platform.Domain.csproj" />
    <ProjectReference Include="..\Platform.Infrastructure\Platform.Infrastructure.csproj" />
    <ProjectReference Include="..\Platform.Shared\Platform.Shared.csproj" />
  </ItemGroup>

</Project>
